const KEY='kids-smart-coins-v1';const blank={coins:0,stars:0,step:0,savings:0,kind:0,items:[],log:[],missionsDone:[],jobsDone:0,day:1,energy:3,jobHistory:[],budget:{saved:0,joy:0,giving:0,learning:0}};let state;try{state={...blank,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{state={...blank}}let tab='adventure',feedback='',answered=false,missionIndex=0,missionChoice=null;let soundEnabled=false,ctx=null,lastStory='';let voiceRate=1.6;const canSpeak=('speechSynthesis' in window)&&('SpeechSynthesisUtterance' in window);
function tone(success=true){if(!soundEnabled)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;ctx=ctx||new C();if(ctx.state==='suspended')ctx.resume();[0,1,2].forEach((n)=>{let o=ctx.createOscillator(),g=ctx.createGain(),start=ctx.currentTime+n*.11;o.type='sine';o.frequency.value=(success?[523,659,784]:[330,294,262])[n];g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(.075,start+.015);g.gain.exponentialRampToValueAtTime(.0001,start+.15);o.connect(g);g.connect(ctx.destination);o.start(start);o.stop(start+.17)})}catch(e){}}
function speak(t){if(!soundEnabled||!canSpeak)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='ru-RU';u.rate=voiceRate;u.pitch=1.12;speechSynthesis.speak(u)}catch(e){}}
function setVoiceRate(v){voiceRate=Number(v)||1.6;try{speechSynthesis.cancel()}catch(e){}if(soundEnabled)speak('Теперь я говорю быстрее!')}
function toggleSound(){soundEnabled=!soundEnabled;try{speechSynthesis.cancel()}catch(e){}updateAudio();if(soundEnabled){tone();speak('Привет! Я Лисёнок Копеечка. Нажми прочитать задание, и я помогу тебе.')} }
function updateAudio(){const b=document.getElementById('soundToggle');b.textContent=soundEnabled?'🔊 Звук включён':'🔇 Звук выключен';b.setAttribute('aria-pressed',String(soundEnabled));const rd=document.getElementById('readButton');rd.textContent=canSpeak?'🔊 Прочитать задание':'🔈 Чтение недоступно';rd.disabled=!canSpeak}
function readCurrent(){if(!canSpeak)return;if(!soundEnabled){soundEnabled=true;updateAudio()}let t='';if(tab==='adventure'){const q=QUESTS[state.step];t=q?(answered?(feedback==='try'?'Попробуй ещё раз!':q[5]):q[1]+'. Первый вариант: '+q[2]+'. Второй вариант: '+q[3]):'Ура! Ты прошёл все приключения!'}else if(tab==='city'){t='В городе выбирай работу, составляй бюджет или заканчивай игровой день.'}else if(tab==='missions'){const m=MISSIONS[missionIndex];t=missionChoice===null?m.story+'. '+m.question+'. Первый вариант: '+m.choices[0].label+'. Второй вариант: '+m.choices[1].label:m.choices[missionChoice].result}else if(tab==='shop'){t='Это магазин. Подумай, что хочешь купить.'}else if(tab==='dream'){t='Это копилка. Здесь можно откладывать монеты.'}else{t='Это остров добрых дел. Можно помочь друзьям.'}speak(t)}
function celebration(label){lastStory='<div class="story-toast" role="status"><span class="celebrate">🎉✨🎈</span>'+label+'</div>'}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}update()}
function update(){document.getElementById('coins').textContent=state.coins;document.getElementById('stars').textContent=state.stars;document.querySelectorAll('.island').forEach((el,i)=>el.classList.toggle('current',Math.min(4,Math.floor(state.step/3))===i))}
function show(next){try{speechSynthesis.cancel()}catch(e){}tab=next;feedback='';answered=false;missionChoice=null;document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.getElementById(({adventure:'tabAdventure',city:'tabCity',missions:'tabMissions',shop:'tabShop',dream:'tabDream',help:'tabHelp'})[tab]).classList.add('active');render()}
function render(){update();updateAudio();const v=document.getElementById('view');if(tab==='adventure'){if(state.step>=QUESTS.length){v.innerHTML='<div class="big">🏆🎉</div><h2>Ты прошёл все приключения!</h2><p>Отличная работа! Ты научился заботиться о деньгах и людях. Можно пройти вопросы ещё раз и заработать новые звёзды.</p><div class="center"><button class="primary" onclick="replay()">Повторить приключение</button></div>';return}const q=QUESTS[state.step];v.innerHTML='<div class="guide"><span class="character">🦊</span><span>Привет! Я Лисёнок Копеечка. Нажми «Прочитать задание», если нужна помощь!</span></div>'+lastStory+'<div class="center">Задание '+(state.step+1)+' из '+QUESTS.length+'</div><div class="progress"><div style="width:'+(state.step/QUESTS.length*100)+'%"></div></div><div class="big">'+q[0]+'</div><h2>'+q[1]+'</h2>'+(answered?'<div class="feedback '+(feedback==='try'?'try':'')+'">'+(feedback==='try'?'Подумаем ещё! 🌱':q[5])+'</div><div class="center"><button class="primary" onclick="next()">Дальше →</button></div>':'<div class="answers"><button class="choice" onclick="answer(0)">'+q[2]+'</button><button class="choice" onclick="answer(1)">'+q[3]+'</button></div><p class="notice">За ответ получишь ⭐ звезду и 5 🪙 монет. Ошибаться можно!</p>');return}
if(tab==='city'){renderCity(v);return}if(tab==='missions'){renderMission(v);return}if(tab==='shop'){const items=[['✏️','Цветные карандаши',15],['🧩','Пазл',25],['🛴','Самокат',55],['📚','Книжка',20]];v.innerHTML='<div class="big">🛍️</div><h2>Магазин разумных покупок</h2><p>Подумай, чего ты действительно хочешь. У тебя '+state.coins+' монет.</p><div class="shop">'+items.map((it,i)=>'<div class="item"><div class="emoji">'+it[0]+'</div><h3>'+it[1]+'</h3><div>🪙 '+it[2]+'</div><button '+(state.coins<it[2]?'disabled':'')+' onclick="buy('+i+')">Купить</button></div>').join('')+'</div><p class="notice">'+(feedback||'Покупки здесь игровые — ничего настоящего оплачивать не нужно.')+'</p>';return}
if(tab==='dream'){v.innerHTML='<div class="big">🐷🚲</div><h2>Мечта: велосипед</h2><p>Чтобы накопить на велосипед, собери 50 монет в копилке.</p><div class="progress"><div style="width:'+Math.min(100,state.savings*2)+'%"></div></div><p>Накоплено '+state.savings+' из 50 монет</p><div class="center"><button class="primary" '+(state.coins<5?'disabled':'')+' onclick="deposit()">Отложить 5 🪙</button></div><p class="notice">'+(state.savings>=50?'🎉 Ты достиг цели! Терпение помогло тебе накопить на мечту.':feedback||'В копилке монеты не пропадают — они ждут твою цель.')+'</p>';return}
v.innerHTML='<div class="big">💚🤝</div><h2>Остров добрых дел</h2><p>Можешь поделиться 5 монетами, чтобы купить семена для общего сада.</p><div class="center"><button class="primary" '+(state.coins<5?'disabled':'')+' onclick="give()">Подарить 5 🪙</button></div><p>🌱 Добрых дел: '+state.kind+'</p><p class="notice">'+(feedback||'Помогать другим можно не только деньгами, но и временем, вниманием и заботой.')+'</p>'}



function answer(i){if(answered)return;lastStory='';const q=QUESTS[state.step];answered=true;if(i===q[4]){state.coins+=5;state.stars++;feedback='ok';tone(true);speak('Молодец! '+q[5])}else{feedback='try';tone(false);speak('Ничего страшного! Попробуй другой вариант.')}save();render()}
function next(){if(!answered)return;if(feedback==='try'){answered=false;feedback='';render();return}state.step++;if(state.step%3===0){celebration('Новый остров покорён! Ты прекрасно справляешься!');tone(true);speak('Ура! Новый остров открыт!')}else{lastStory=''}save();answered=false;feedback='';render()}
function replay(){state.step=0;lastStory='';save();render()}
function buy(i){const it=[['✏️','Цветные карандаши',15],['🧩','Пазл',25],['🛴','Самокат',55],['📚','Книжка',20]][i];if(state.coins<it[2])return;state.coins-=it[2];state.items.push(it[1]);feedback='🎉 Куплено: '+it[1]+'. Ты сам сделал выбор!';tone();speak('Отлично! Покупка совершена!');save();render()}
function deposit(){if(state.coins<5)return;state.coins-=5;state.savings+=5;tone();speak(state.savings>=50?'Ура! Ты накопил на велосипед!':'Молодец! Ты отложил пять монет.');save();render()}
function give(){if(state.coins<5)return;state.coins-=5;state.kind++;feedback='Спасибо! Ты помог вырастить сад 🌱';tone();speak('Спасибо за твою доброту!');save();render()}
show('adventure');
