const CITY_PLACES=[['🏠','Дом','Отдых и забота'],['🛠️','Профессии','Полезный труд'],['💰','Бюджет','Распределяем монеты'],['🏪','Магазин','Разумные покупки'],['🐷','Копилка','Большая мечта']];
let cityPlace=null,jobStage=0,selectedJob=-1,jobAttempt=false,cityMessage='';
const WORK=[
{emoji:'🎨',name:'Художник',intro:'Нарисуем открытку для ярмарки. Что понадобится?',choices:['📄 Бумага и карандаши','🎈 Только шарики'],correct:0,explain:'Отлично! Открытка готова и приносит радость покупателю.'},
{emoji:'🌱',name:'Садовник',intro:'Растению нужно помочь вырасти. Что сделаем?',choices:['💧 Польём росток','🧸 Подарим ростку игрушку'],correct:0,explain:'Ты позаботился о ростке. Терпение и труд помогают ему расти.'},
{emoji:'📦',name:'Помощник магазина',intro:'Покупатель просит два яблока. Что положим в корзинку?',choices:['🍎 Одно яблоко','🍎🍎 Два яблока'],correct:1,explain:'Ты правильно собрал заказ и помог покупателю!'}
];
function workReady(){return state.energy>0}
function renderCity(v){
const d=state.day||1,e=state.energy??3;
const back='<div class="center"><button class="secondary" onclick="cityPlace=null;cityMessage=\'\';render()">← К городу</button></div>';
const top='<div class="daybar">📅 День '+d+' · '+(e===3?'☀️ Утро':e===2?'🌤️ День':e===1?'🌇 Вечер':'🌙 Время отдыхать')+' · ⚡ Дела: '+e+'/3</div>';
if(cityPlace===null){
v.innerHTML=top+'<h2>🏘️ Город умных монет</h2><p>Каждый день можно выполнить три полезных дела. Потом нужен отдых!</p><div class="city-grid">'+CITY_PLACES.map((p,i)=>'<button class="city-card" onclick="enterCity('+i+')"><span>'+p[0]+'</span><strong>'+p[1]+'</strong><small>'+p[2]+'</small></button>').join('')+'</div><div class="center"><button class="primary" onclick="newDay()">🌙 Закончить день и отдохнуть</button></div><p class="notice">'+cityMessage+'</p>';return}
if(cityPlace===0){v.innerHTML=top+'<div class="big">🏠</div><h2>Уютный дом</h2><p>Помогать дома и отдыхать полезно. За заботу о близких не обязательно получать деньги.</p><div class="center"><button class="primary" onclick="homeKind()">💚 Помочь убрать игрушки</button></div><p id="homeMessage" class="notice">'+cityMessage+'</p>'+back;return}
if(cityPlace===1){if(selectedJob<0){v.innerHTML=top+'<h2>🛠️ Выбери профессию</h2><p>Сначала сделаем что-то полезное, а затем получим 5 монет.</p><div class="city-grid">'+WORK.map((w,i)=>'<button class="city-card" onclick="selectWork('+i+')" '+(!workReady()?'disabled':'')+'><span>'+w.emoji+'</span><strong>'+w.name+'</strong><small>5 🪙 · 1 дело</small></button>').join('')+'</div><p class="notice">'+(workReady()?'Выбирай дело, которое интересно.':'Сегодня дела закончились. Пора отдыхать!')+'</p>'+back;return}
const w=WORK[selectedJob];v.innerHTML=top+'<div class="big">'+w.emoji+'</div><h2>'+w.name+'</h2><p>'+w.intro+'</p><div class="answers">'+w.choices.map((choice,i)=>'<button class="choice" onclick="finishWork('+i+')" '+(jobAttempt?'disabled':'')+'>'+choice+'</button>').join('')+'</div><div class="feedback '+(cityMessage.startsWith('Попробуй')?'try':'')+'">'+(cityMessage||'Выбери подходящий ответ.')+'</div><div class="center"><button class="secondary" onclick="selectedJob=-1;cityMessage=\'\';render()">← Все профессии</button></div>';return}
if(cityPlace===2){
const b=state.budget||{saved:0,joy:0,giving:0,learning:0};
v.innerHTML=top+'<div class="big">💰</div><h2>Мой первый бюджет</h2><p>Сейчас свободно: '+state.coins+' 🪙. Выбери, куда положить 5 монет.</p><div class="city-grid">'+[['🐷','На мечту','saved'],['🎈','На радость','joy'],['💚','На добрые дела','giving'],['📚','На развитие','learning']].map(p=>'<button class="city-card" '+(state.coins<5?'disabled':'')+' onclick="budgetFive(\''+p[2]+'\')"><span>'+p[0]+'</span><strong>'+p[1]+'</strong><small>Отложить 5 🪙</small></button>').join('')+'</div><p class="budget-line">🐷 '+b.saved+' · 🎈 '+b.joy+' · 💚 '+b.giving+' · 📚 '+b.learning+'</p><p class="notice">'+(cityMessage||'Эти монеты теперь распределены по разным целям.')+'</p>'+back;return}
if(cityPlace===3){v.innerHTML=top+'<div class="big">🏪</div><h2>Магазин</h2><p>Перед покупкой проверь, хватит ли монет и останется ли что-нибудь на мечту.</p><div class="center"><button class="primary" onclick="show(\'shop\')">🛍️ Открыть магазин</button></div>'+back;return}
v.innerHTML=top+'<div class="big">🐷</div><h2>Копилка мечты</h2><p>В копилке уже '+state.savings+' монет!</p><div class="center"><button class="primary" onclick="show(\'dream\')">🐷 Открыть копилку</button></div>'+back;
}
function enterCity(i){cityPlace=i;selectedJob=-1;jobAttempt=false;cityMessage='';render();if(soundEnabled)speak(CITY_PLACES[i][1])}
function selectWork(i){if(!workReady())return;selectedJob=i;jobAttempt=false;cityMessage='';render();if(soundEnabled)speak(WORK[i].intro)}
function finishWork(i){if(jobAttempt||!workReady())return;const w=WORK[selectedJob];if(i!==w.correct){cityMessage='Попробуй ещё раз. Можно ошибаться!';speak('Подумай ещё.');render();return}jobAttempt=true;state.energy--;state.coins+=5;state.jobsDone=(state.jobsDone||0)+1;state.jobHistory=(state.jobHistory||[]).concat([{day:state.day,job:w.name}]).slice(-20);cityMessage='🎉 '+w.explain+' Ты заработал 5 монет!';save();tone();speak('Молодец! Ты заработал пять монет.');render()}
function newDay(){state.day=(state.day||1)+1;state.energy=3;selectedJob=-1;cityPlace=null;cityMessage='☀️ Новый день! Ты отдохнул и снова можешь помогать жителям.';save();tone();render();speak('Доброе утро! Новый день начинается!')}
function budgetFive(type){if(state.coins<5)return;const valid=['saved','joy','giving','learning'];if(!valid.includes(type))return;state.budget=state.budget||{saved:0,joy:0,giving:0,learning:0};state.coins-=5;state.budget[type]=(state.budget[type]||0)+5;if(type==='saved')state.savings+=5;if(type==='giving')state.kind++;cityMessage='Ты распределил 5 монет. Подумай, зачем нужен каждый конверт.';save();tone();render()}
function homeKind(){cityMessage='💚 Спасибо! Забота о доме важна и без денежной награды.';render();speak('Помогать дома — доброе дело.')}
