const CITY_PLACES=[['🏠','Дом','Забота и отдых'],['🛠️','Мастерская','Полезный труд'],['🏪','Магазин','Обдуманные покупки'],['🐷','Копилка','Большая мечта']];
let cityPlace=null,jobStage=0;
function renderCity(v){if(cityPlace===null){v.innerHTML='<div class="city-heading"><h2>🏘️ Город умных монет</h2><p>Куда отправимся сегодня? Выбирай домик!</p></div><div class="city-scene"><div class="city-sun">☀️</div><div class="city-cloud">☁️</div><div class="city-houses">'+CITY_PLACES.map((p,i)=>'<button class="city-house" onclick="enterCity('+i+')"><span class="city-emoji">'+p[0]+'</span><strong>'+p[1]+'</strong><small>'+p[2]+'</small></button>').join('')+'</div><div class="city-road">🚶 🌳 🌼 🌳</div></div><p class="notice">Можешь возвращаться в любой домик в любое время.</p>';return}
const back='<div class="center"><button class="secondary" onclick="cityPlace=null;render()">← На карту города</button></div>';
if(cityPlace===0){v.innerHTML='<div class="big">🏠🧸</div><h2>Наш уютный дом</h2><p>Лисёнок напоминает: отдых, помощь близким и игры с друзьями тоже очень ценны. Не всё хорошее покупается за монеты!</p><div class="center"><button class="primary" onclick="homeKind()">Помочь убрать игрушки 💚</button></div><p id="homeMessage" class="notice"></p>'+back;return}
if(cityPlace===1){v.innerHTML='<div class="big">🛠️🎨</div><h2>Мастерская полезных дел</h2><p>Помоги Лисёнку подготовить открытки для ярмарки. Сначала выбери, что ему понадобится.</p><div class="answers"><button class="choice" onclick="doJob(0)">🎨 Бумага и карандаши</button><button class="choice" onclick="doJob(1)">🎈 Только воздушные шарики</button></div><p class="notice" id="jobMessage">За полезное дело можно получить 5 игровых монет. Всего одно задание за посещение мастерской.</p>'+back;return}
if(cityPlace===2){v.innerHTML='<div class="big">🏪</div><h2>Магазин на площади</h2><p>Здесь можно сравнить желания и возможности. Купить игрушку — тоже нормальный выбор, когда ты подумал о бюджете.</p><div class="center"><button class="primary" onclick="show(&quot;shop&quot;)">Выбрать покупку →</button></div>'+back;return}
v.innerHTML='<div class="big">🐷🚲</div><h2>Домик копилки</h2><p>Маленькие накопления приближают большую мечту. Ты уже накопил '+state.savings+' монет!</p><div class="center"><button class="primary" onclick="show(&quot;dream&quot;)">Открыть копилку →</button></div>'+back}
function enterCity(i){cityPlace=i;jobStage=0;render();if(soundEnabled){speak(CITY_PLACES[i][1]+'. '+CITY_PLACES[i][2])}}
function homeKind(){document.getElementById('homeMessage').textContent='💚 Спасибо! Забота о доме важна сама по себе, даже без денежной награды.';tone();speak('Отлично! Помогать дома — это тоже доброе дело.')}
function doJob(i){const el=document.getElementById('jobMessage');if(jobStage)return;if(i===1){el.textContent='Шарики красивые, но для открыток нужны бумага и карандаши. Попробуй ещё!';speak('Подумай, чем рисуют открытки.');return}jobStage=1;state.jobsDone=(state.jobsDone||0)+1;state.coins+=5;save();tone();el.textContent='🎉 Открытки готовы! Ты заработал 5 монет полезным делом.';speak('Ты помог сделать открытки и заработал пять монет!');}

